#!/bin/bash
        ret=$(ps | grep [c]at | wc -l)
        if [ "$ret" -eq 0 ]
then {
        echo "FAULT. No active connections."
        exit 1
}
else 
{
        echo "Sending..."
 echo  "-DNS-$(curl -s 'https://newsapi.org/v2/top-headlines?country=ru&pagesize=10&apiKey=959e3d5d1ca54704995cf2a1b6659841' | jq '.articles[0,1,2,3,4,5,6,7,8,9].title')">/dev/ttyUSB0

        sleep 1
        exit 1
}
fi;


