#!/bin/bash
text=$*
text=$(sed 's/–/-/g' <<<$text)
text=$(sed 's/ / /g' <<<$text)
text=$(sed 's/[«»]/"/g' <<<$text)
ret=$(cat /conn)
if [ "$ret" -eq 0 ]
then {
        echo "FAULT. No active connections."
        exit 1
}
else
{
        echo -n "$text">/dev/ttyUSB0
        echo "Sent"
        sleep 1
        exit 0
}
fi;
