#!/bin/bash
text=$*
text=$(sed 's/–/-/g' <<<$text)
text=$(sed 's/[^[:print:]]//g' <<<$text)
text=$(sed 's/[  ]/ /g' <<<$text)
text=$(sed 's/[«»]/"/g' <<<$text)
text=$(sed 's/[^[:alnum:]^[:space:]^[:punct:]]//g' <<<$text)
ret=$(cat /conn)
if [ "$ret" -eq 0 ]
then {
        echo "FAULT. No active connections."
        exit 1
}
else
{
        echo -n "$text">/dev/ttyUSB0
        #echo "Sent"
        echo $text
        sleep 1
        exit 0
}
fi;
